version: '3'
services:
  converter:
    build: ./converter
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./converter/scripts:/converter/scripts
      - /srv/excli/var/www/files:/var/www/files  
    environment:
      - FLASK_DEBUG
    networks:
      - nginx

networks:
  nginx:      
    external: true    
